<div class="page-header">
    <h1 class="entry-title">SISTEM PENDUKUNG KEPUTUSAN PROGRAM KELUARGA HARAPAN KELURAHAN KENDARI CADDI</h1>
</div>
<div class="entry-body">
	<h3 class=" mt-3">APA ITU PROGRAM KELUARGA HARAPAN</h3>
  <hr class="mb-5">

  <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Program Keluarga Harapan yang selanjutnya disebut PKH adalah program pemberian ba</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">n</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">tuan sosial bersyarat kepada </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Keluarga Miskin (KM)</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> yang ditetapkan sebagai </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">keluarga penerima manfaat </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">PKH.</span></span></span></p>

  <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sebagai upaya percepatan penanggulangan kemiskinan, sejak tahun 2007 Pemerintah Indone&shy;sia telah melaksanakan PKH. Program </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">P</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">erlindungan </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">osial yang juga dikenal di dunia internasional dengan istilah <em>Conditional Cash Transfers</em> (CCT) ini terbukti cukup berhasil dalam menanggulangi kemiskinan yang dihadapi di negara-negara tersebut, terutama masalah kemiskinan kronis.</span></span></span></p>

  <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sebagai </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">sebuah </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">program bantuan </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">sosial </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">bersyarat, </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">PKH </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">membuka akses keluarga </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">miskin</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> terutama ibu hamil dan anak untuk memanfaatkan berbagai fasilitas layanan kesehatan (</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">f</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">askes) dan fasilitas layanan pendidikan (</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">f</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">asdik) yang tersedia di sekitar mereka. </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Manfaat PKH juga mulai didorong untuk mencakup </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">penyandang disabilitas dan lanjut usia dengan mempertahankan taraf kesejahteraan sosialnya sesuai dengan amanat konstitusi dan Nawacita Presiden RI. </span></span></span></p>

  <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Melalui</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> PKH</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">, KM didorong untuk memiliki akses dan memanfaatkan </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;pelayanan sosial dasar kesehatan, pendidikan, pangan dan gizi, </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">perawatan</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">,</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> dan </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">pendampingan</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">, termasuk akses terhadap berbagai program perlindungan sosial lainnya yang merupakan program komplementer secara berkelanjutan. PKH </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">diarahkan</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> untuk menjadi episentrum dan <em>center of excellence</em> penanggulangan kemiskinan yang mensinergika</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">n </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">berbagai program perlindungan dan pemberdayaan sosial nasional</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">.</span> </span></span></p>

  <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Misi besar PKH untuk menurunkan kemiskinan </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">semakin </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">mengemuka mengingat jumlah </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">penduduk</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> miskin Indonesia</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> sampai pada Maret tahun 2016</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> masih sebesar 1</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">0</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">,</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">86</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">% dari total </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">penduduk atau 28,01 juta jiwa (BPS, 2016). </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pemerintah telah menetapkan target penurunan kemiskinan menjadi 7-8% pada tahun 2019</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">,</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> sebagaimana tertuang di dalam RPJMN 2015-2019. PKH diharapkan dapat berkontribusi secara signifikan untuk menurunkan jumlah penduduk miskin, menurunkan kesen</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">j</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">angan (<em>gini ra</em></span><em><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">t</span></em><em><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">io</span></em><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">) seraya meningkatkan </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Indeks Pembangunan Manusia (</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">IPM</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">)</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">.</span></span></span></p>

  <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Hasil </span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">penelitian</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> lain menunjukkan bahwa PKH memberikan dampak terhadap perubahan konsumsi rumah tangga, seperti di beberapa negara pelaksana CCT lainnya. PKH berhasil meningkatkan konsumsi rumah tangga penerima manfaat di Indonesia sebesar 4,8%.</span></span></span></p>
  <div class="row">
  	<div class="col-md-12">
  		<!-- <img src="assets/pkh.webp" style="width: 90%"> -->
  	</div>
  </div>

</div>